/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flexdesktop.user.GraphicInterface;

import com.flexdesktop.connections.restfulConnection;
import com.flexdesktop.user.Error.InfError;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.Timer;

/**
 *
 * @author Jason
 */
public class CreateAccount extends javax.swing.JDialog {

    /**
     * Creates new form EditRoutes
     *
     * @param parent
     * @param modal
     */
    private final Point point = new Point(0, 0);

    private String[] columName = {"Beneficiarios"};

    public List<Object[]> beneciarios = new ArrayList<Object[]>();

    private int accion = 0;
    private final int BORRAR = 1;
    private final int Ver = 0;
    private final int Actualizar = 2;
    private int idProposito;

    public CreateAccount(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        configureTableLook();//no hace nada

        this.jTable_Dirreciones.setModel(new tableModelAddres(columName,
                beneciarios, true));

        //      DefaultTableModel model = (DefaultTableModel) table.getModel();
//        try {
//            ResultSet resultRoutes = MyDb.getRoutes();
//
//            while (resultRoutes.next()) {
//                String nombre_ruta = resultRoutes.getString("nombre_ruta");
//                String numero_ruta = resultRoutes.getString("idRuta");
//                Object[] datos = {nombre_ruta + " " + numero_ruta, false, numero_ruta};
//                model.addRow(datos);
//            }
//
//        } catch (SQLException ex) {
//            System.out.println("Error al cargar rutas");
//        }
        //completarTablaFacturacion();
    }

    public void showDialog(String panel) {

        final Timer timer = new Timer(30, null);
        timer.setRepeats(true);
        timer.addActionListener(new ActionListener() {
            private float opacity = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                opacity += 0.15f;
                setOpacity(Math.min(opacity, 1));
                if (opacity >= 1) {
                    timer.stop();
                }
            }
        });
        setOpacity(0);
        timer.start();

        setVisiblePanel(panel);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCearCuentaAhorroVista = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jFormattedTextFieldEnterName = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldEnterCedula = new javax.swing.JFormattedTextField();
        jLabelDescrip = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Dirreciones = new javax.swing.JTable();
        jLabelBuscaridCliente = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jFormattedTextFieldCIFBenefi = new javax.swing.JFormattedTextField();
        jPanelCrearCuentaObjetivo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldCIFAhorroObjetivo = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelDescrip1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldPeriodicidad = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dateChooserComboInit = new datechooser.beans.DateChooserCombo();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextFieldMontoAhorro = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCuentaDebito = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabelBuscaridCliente2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jFormattedTextFieldProposito = new javax.swing.JFormattedTextField();
        jLabelBuscaridCliente3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jComboBox3 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(418, 578));
        setUndecorated(true);

        jPanelCearCuentaAhorroVista.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCearCuentaAhorroVista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCearCuentaAhorroVista.setMaximumSize(new java.awt.Dimension(418, 578));
        jPanelCearCuentaAhorroVista.setMinimumSize(new java.awt.Dimension(418, 578));
        jPanelCearCuentaAhorroVista.setPreferredSize(new java.awt.Dimension(418, 578));
        jPanelCearCuentaAhorroVista.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelCearCuentaAhorroVistaMouseDragged(evt);
            }
        });
        jPanelCearCuentaAhorroVista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelCearCuentaAhorroVistaMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Khmer UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Cuenta Ahorro a la Vista");

        jLabel7.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Crear Cuenta");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.setOpaque(true);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2_roller.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jFormattedTextFieldEnterName.setCaretColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldEnterName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldEnterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldEnterNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CIF Cliente:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Moneda:");

        jFormattedTextFieldEnterCedula.setCaretColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldEnterCedula.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldEnterCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldEnterCedulaActionPerformed(evt);
            }
        });

        jLabelDescrip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDescrip.setText("Descripción:");

        jButton8.setText("Agregar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setText("Borrar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTable_Dirreciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_Dirreciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Dirreciones.setCellSelectionEnabled(true);
        jTable_Dirreciones.setFillsViewportHeight(true);
        jTable_Dirreciones.setSurrendersFocusOnKeystroke(true);
        jTable_Dirreciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_DirrecionesKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Dirreciones);
        jTable_Dirreciones.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabelBuscaridCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscaridCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/Images/Buttons/searchLttBlckBtt.png"))); // NOI18N
        jLabelBuscaridCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBuscaridClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBuscaridClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBuscaridClienteMouseExited(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "$", "₡" }));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/1390186347_tests.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/atras.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/hecho.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCearCuentaAhorroVistaLayout = new javax.swing.GroupLayout(jPanelCearCuentaAhorroVista);
        jPanelCearCuentaAhorroVista.setLayout(jPanelCearCuentaAhorroVistaLayout);
        jPanelCearCuentaAhorroVistaLayout.setHorizontalGroup(
            jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                .addGroup(jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelBuscaridCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelDescrip)
                                    .addComponent(jFormattedTextFieldEnterCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jFormattedTextFieldCIFBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCearCuentaAhorroVistaLayout.setVerticalGroup(
            jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                        .addGroup(jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addGroup(jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBuscaridCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)))
                .addGap(20, 20, 20)
                .addGroup(jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jLabelDescrip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldEnterCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jFormattedTextFieldCIFBenefi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCearCuentaAhorroVistaLayout.createSequentialGroup()
                        .addGroup(jPanelCearCuentaAhorroVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelCrearCuentaObjetivo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCrearCuentaObjetivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCrearCuentaObjetivo.setMaximumSize(new java.awt.Dimension(418, 578));
        jPanelCrearCuentaObjetivo.setMinimumSize(new java.awt.Dimension(418, 578));
        jPanelCrearCuentaObjetivo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelCrearCuentaObjetivoMouseDragged(evt);
            }
        });
        jPanelCrearCuentaObjetivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelCrearCuentaObjetivoMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Khmer UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Cuenta Ahorro Por Objetivo");

        jLabel8.setFont(new java.awt.Font("Khmer UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Crear Cuenta");

        jFormattedTextFieldCIFAhorroObjetivo.setCaretColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldCIFAhorroObjetivo.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jFormattedTextFieldCIFAhorroObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCIFAhorroObjetivoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CIF Cliente:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Proposito:");

        jLabelDescrip1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDescrip1.setText("Fecha Ahorro:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Periodicidad:");

        jFormattedTextFieldPeriodicidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldPeriodicidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldPeriodicidadFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Desde:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Duración:");

        dateChooserComboInit.setCurrentView(new datechooser.view.appearance.AppearancesList("Grey",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserComboInit.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));

    jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel13.setText("Monto Ahorro:");

    jFormattedTextFieldMontoAhorro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

    jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel14.setText("Cuenta Debito: ");

    jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/1390186347_tests.png"))); // NOI18N

    jLabelBuscaridCliente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelBuscaridCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/Images/Buttons/searchLttBlckBtt.png"))); // NOI18N
    jLabelBuscaridCliente2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabelBuscaridCliente2MouseClicked(evt);
        }
    });

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/atras.png"))); // NOI18N
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/hecho.png"))); // NOI18N
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    jButton6.setBackground(new java.awt.Color(255, 255, 255));
    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2.png"))); // NOI18N
    jButton6.setContentAreaFilled(false);
    jButton6.setFocusable(false);
    jButton6.setOpaque(true);
    jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/user/Images/close2_roller.png"))); // NOI18N
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });

    jFormattedTextFieldProposito.setEditable(false);

    jLabelBuscaridCliente3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelBuscaridCliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/Images/Buttons/searchLttBlckBtt.png"))); // NOI18N
    jLabelBuscaridCliente3.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabelBuscaridCliente3MouseClicked(evt);
        }
    });

    jFormattedTextField1.setText("0");

    jLabel3.setText("días");

    jLabel17.setText("Moneda:");

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "$", "₡" }));

    jLabel18.setText("MontoAhorroPeriodico:");

    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "segundos", "minutos", "horas", "dias", "meses" }));

    javax.swing.GroupLayout jPanelCrearCuentaObjetivoLayout = new javax.swing.GroupLayout(jPanelCrearCuentaObjetivo);
    jPanelCrearCuentaObjetivo.setLayout(jPanelCrearCuentaObjetivoLayout);
    jPanelCrearCuentaObjetivoLayout.setHorizontalGroup(
        jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jFormattedTextFieldCIFAhorroObjetivo, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldProposito))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelBuscaridCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelBuscaridCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                    .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabelDescrip1))))
                        .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(112, 112, 112))
                                .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                                    .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dateChooserComboInit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(57, 57, 57)))
                            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFormattedTextField1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                                    .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jFormattedTextFieldMontoAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCuentaDebito))))
                            .addGap(0, 0, Short.MAX_VALUE)))))
            .addContainerGap())
    );
    jPanelCrearCuentaObjetivoLayout.setVerticalGroup(
        jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                    .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addComponent(jButton6))
                    .addGap(27, 27, 27)
                    .addComponent(jLabel5)
                    .addGap(51, 51, 51)
                    .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldCIFAhorroObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelBuscaridCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldProposito)))
                .addComponent(jLabelBuscaridCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jFormattedTextFieldPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(38, 38, 38)
            .addComponent(jLabelDescrip1)
            .addGap(18, 18, 18)
            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(jLabel12))
            .addGap(18, 18, 18)
            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dateChooserComboInit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelCrearCuentaObjetivoLayout.createSequentialGroup()
                    .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGap(9, 9, 9)))
            .addGap(19, 19, 19)
            .addComponent(jLabel17)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jFormattedTextFieldMontoAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(26, 26, 26)
            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextFieldCuentaDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanelCrearCuentaObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanelCrearCuentaObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanelCearCuentaAhorroVista, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanelCrearCuentaObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jPanelCearCuentaAhorroVista, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (validateUI()) {
            String CIF = jFormattedTextFieldEnterName.getText();
            int moneda = 1;
            if (jComboBox1.selectWithKeyChar('$')) {
                moneda = 2;
            }

            String cuenta = restfulConnection.postRESTful("http://localhost:52003/api/cbcuenta"
                    + "/crearCuentaDebito?CIF=" + CIF + "&descripcion="
                    + jFormattedTextFieldEnterCedula.getText() + "&moneda="
                    + moneda,
                    "");
            cuenta = cuenta.substring(1, cuenta.length() - 2);

            if (!beneciarios.isEmpty()) {

                for (int i = 0; i < beneciarios.size(); i++) {

                    restfulConnection.postRESTful("http://localhost:52003/api/CBBeneficiario/agregarBeneficia"
                            + "rosCuentaDebito?CIF=" + beneciarios.get(i)[0].toString() + "&numCuenta=" + cuenta,
                            "");
                }
            }

            dispose();

        } else {
            InfError.showMessage(this, " Atención: Faltan Algunos Campos "
                    + "Por Rellenar");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanelCearCuentaAhorroVistaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCearCuentaAhorroVistaMouseDragged
        if (!evt.isMetaDown()) {
            Point p = getLocation();
            setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
        }
    }//GEN-LAST:event_jPanelCearCuentaAhorroVistaMouseDragged

    private void jPanelCearCuentaAhorroVistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCearCuentaAhorroVistaMousePressed
        if (!evt.isMetaDown()) {
            point.x = evt.getX();
            point.y = evt.getY();
        }
    }//GEN-LAST:event_jPanelCearCuentaAhorroVistaMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jFormattedTextFieldEnterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEnterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldEnterNameActionPerformed

    private void jFormattedTextFieldEnterCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldEnterCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldEnterCedulaActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            eliminarFila(jTable_Dirreciones);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

//        getInformation getInfoPanel = new getInformation(null, true);
//        getInfoPanel.setActionIcon(8);
//        getInfoPanel.SetTittle("Consultar Beneficiario");
//        getInfoPanel.showDialog("CreateBneficiario");
//        String CIF = getInfoPanel.getCIF();
//        String[] benefi = {CIF};
        String[] benefi = {jFormattedTextFieldCIFBenefi.getText()};

        beneciarios.add(benefi);
        if (!"".equals(jFormattedTextFieldCIFBenefi.getText())) {
            this.jTable_Dirreciones.setModel(new tableModelAddres(columName,
                    beneciarios, true));
        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable_DirrecionesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_DirrecionesKeyPressed
        int tecla = evt.getKeyCode();
        if (tecla == KeyEvent.VK_F9) {
            //   this.eliminarFila();
        } else {
            // hotKeyPressEvt(evt);
        }
    }//GEN-LAST:event_jTable_DirrecionesKeyPressed

    private void jLabelBuscaridClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaridClienteMouseEntered
        jLabelBuscaridCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/Images/Buttons/searchLttBtt.png")));
    }//GEN-LAST:event_jLabelBuscaridClienteMouseEntered

    private void jLabelBuscaridClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaridClienteMouseExited
        jLabelBuscaridCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flexdesktop/Images/Buttons/searchLttBlckBtt.png")));
    }//GEN-LAST:event_jLabelBuscaridClienteMouseExited

    private void jLabelBuscaridClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaridClienteMouseClicked
        getInformation getInfoPanel = new getInformation(null, true);
        getInfoPanel.setActionIcon(8);
        getInfoPanel.SetTittle("Consultar Cliente");
        getInfoPanel.showDialog("ConsultarClt");
        String ced = getInfoPanel.getCIF();
        if (ced != "") {
            jFormattedTextFieldEnterName.setText(ced);
        }

    }//GEN-LAST:event_jLabelBuscaridClienteMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (validateUI2()) {
            String CIF = jFormattedTextFieldCIFAhorroObjetivo.getText();
//            int moneda = 0;
//            if (jComboBox1.selectWithKeyChar('$')) {
//                moneda = 1;
//            }

            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String fechaIni = format.format(
                    dateChooserComboInit.getSelectedDate().getTime());

//            String fechaFin = format.format(
//                    dateChooserComboFin.getSelectedDate().getTime());
//            restfulConnection.postRESTful("http://localhost:52003/api/cbcuenta"
//                    + "/crearCuentaAhorro?CIF=" + CIF + "&idProposito="
//                    + idProposito
//                    + "&Periodicidad=" + jFormattedTextFieldPeriodicidad.getText()
//                    + "&FechaInicio="+fechaIni+"&FechaFinal="+fechaFin+
//                    "&TiempoAhorro="+0+"&MontoAhorroPeriodico="+
//                    jFormattedTextFieldMontoAhorro.getText()+
//                    "&NumeroCuentaOrigen="+jTextFieldCuentaDebito.getText()+
//                    "&Moneda="+1+"& dominioPeriodicidad = & MontoAhorroDeseado",
//                    "");
//            
//            EXEC crearCuentaAhorro
//@ClienteCIF = N'1000000000',
//@idProposito = 1,
//@Periodicidad = 2,
//@FechaInicio = N'10-10-2010',
//@TiempoAhorro = 4,
//@MontoAhorroPeriodico = 4,
//@NumeroCuentaOrigen = 900000000,
//@Moneda = N'1',
//@dominioPeriodicidad = N'dias',
//@MontoAhorroDeseado = 5
            dispose();

        } else {
            InfError.showMessage(this, " Atención: Faltan Algunos Campos "
                    + "Por Rellenar");
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jFormattedTextFieldCIFAhorroObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCIFAhorroObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCIFAhorroObjetivoActionPerformed

    private void jPanelCrearCuentaObjetivoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCrearCuentaObjetivoMouseDragged
        if (!evt.isMetaDown()) {
            Point p = getLocation();
            setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
        }
    }//GEN-LAST:event_jPanelCrearCuentaObjetivoMouseDragged

    private void jPanelCrearCuentaObjetivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCrearCuentaObjetivoMousePressed
        if (!evt.isMetaDown()) {
            point.x = evt.getX();
            point.y = evt.getY();
        }
    }//GEN-LAST:event_jPanelCrearCuentaObjetivoMousePressed

    private void jLabelBuscaridCliente3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaridCliente3MouseClicked
        Object propositos[][];
        showCustomers sC = new showCustomers(null, true);
        sC.setAccionActual(2);
        sC.ocultarBotones("VerListado");

        ArrayList<ArrayList<String>> result = null;

        String[] colums = {"Numero Proposito", "Proposito", "Tasa Interes"};
        sC.setColumName(colums);

        result = cargarPropositos();

        propositos = getInformation.convertToObject(result);

        sC.setClientes(propositos);

        int numeroPaginas = propositos.length / 19;

        int modulo = propositos.length % 19;

        if (modulo != 0) {
            numeroPaginas += 1;
        }

        sC.setNumeroDePaginas(numeroPaginas);
        sC.upDateCostumers();

        sC.initPaginacion();
        sC.showDialog();

        String CIFSelected = sC.getIdSelect();
        ArrayList<String> rowSelected = sC.getRowSelect();
        if (!"".equals(CIFSelected)) {
            idProposito = Math.abs(Integer.parseInt(CIFSelected));
            jFormattedTextFieldProposito.setText(rowSelected.get(1));
        }
    }//GEN-LAST:event_jLabelBuscaridCliente3MouseClicked

    private void jLabelBuscaridCliente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuscaridCliente2MouseClicked
        getInformation getInfoPanel = new getInformation(null, true);
        getInfoPanel.setActionIcon(8);
        getInfoPanel.SetTittle("Consultar Cliente");
        getInfoPanel.showDialog("ConsultarClt");
        String CIF = getInfoPanel.getCIF();
        if (CIF != "") {
            jFormattedTextFieldCIFAhorroObjetivo.setText(CIF);
        }
    }//GEN-LAST:event_jLabelBuscaridCliente2MouseClicked

    private void jFormattedTextFieldPeriodicidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPeriodicidadFocusLost
        try {
            if (Integer.parseInt(jFormattedTextFieldPeriodicidad.getText()) >= 60
                && (jComboBox3.getSelectedItem().toString() == "segundos"
                || jComboBox3.getSelectedItem().toString() == "minutos")) {
            jFormattedTextFieldPeriodicidad.setText("");
        }
        } catch (Exception e) {
             jFormattedTextFieldPeriodicidad.setText("");
        }

    }//GEN-LAST:event_jFormattedTextFieldPeriodicidadFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserComboInit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextFieldCIFAhorroObjetivo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCIFBenefi;
    private javax.swing.JFormattedTextField jFormattedTextFieldEnterCedula;
    private javax.swing.JFormattedTextField jFormattedTextFieldEnterName;
    private javax.swing.JFormattedTextField jFormattedTextFieldMontoAhorro;
    private javax.swing.JFormattedTextField jFormattedTextFieldPeriodicidad;
    private javax.swing.JFormattedTextField jFormattedTextFieldProposito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBuscaridCliente;
    private javax.swing.JLabel jLabelBuscaridCliente2;
    private javax.swing.JLabel jLabelBuscaridCliente3;
    private javax.swing.JLabel jLabelDescrip;
    private javax.swing.JLabel jLabelDescrip1;
    private javax.swing.JPanel jPanelCearCuentaAhorroVista;
    private javax.swing.JPanel jPanelCrearCuentaObjetivo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Dirreciones;
    private javax.swing.JTextField jTextFieldCuentaDebito;
    // End of variables declaration//GEN-END:variables

    private void configureTableLook() {
//        DefaultTableCellRenderer centerRender = new DefaultTableCellRenderer();
//        centerRender.setHorizontalAlignment(JLabel.LEFT);
//
//        table.setRowHeight(25);
//        table.getColumnModel().getColumn(0).setPreferredWidth(60);
//
//        table.getColumnModel().getColumn(1).setPreferredWidth(10);
//        table.getColumnModel().getColumn(0).setCellRenderer(centerRender);
//        //  table.getColumnModel().getColumn(1).setCellRenderer(centerRender);
//
//        TableCellRenderer rendererFromHeader = table.getTableHeader().getDefaultRenderer();
//        JLabel headerLabel = (JLabel) rendererFromHeader;
//        headerLabel.setHorizontalAlignment(JLabel.LEFT);
//
//        table.getTableHeader().setFont(new Font("Khmer UI", Font.PLAIN, 14));
//        table.getTableHeader().setForeground(new Color(102, 102, 102));
    }

    private boolean validateUI() {

        if ("".equals(jFormattedTextFieldEnterName.getText().
                replace(" ", ""))) {

            return false;
        }
//        if (beneciarios.isEmpty()) {
//
//            return false;
//        }
        return true;
    }

    private void showPanelOnDialog(javax.swing.JPanel pPanel, javax.swing.JDialog pDialog) {
        pDialog.add(pPanel);
        pPanel.setVisible(true);
        pDialog.setVisible(true);
    }

    private void setVisiblePanel(String panel) {

        this.setSize(461, 694);
        removePanels();
        switch (panel) {
            case "CuentaAhorro":
                add(jPanelCearCuentaAhorroVista);
                jPanelCearCuentaAhorroVista.setVisible(true);
                jPanelCearCuentaAhorroVista.setLocation(0, 0);
            case "CuentaPorObjetivo":
                add(jPanelCrearCuentaObjetivo);
                jPanelCrearCuentaObjetivo.setVisible(true);
                jPanelCrearCuentaObjetivo.setLocation(0, 0);

        }

    }

    public void removePanels() {
        jPanelCearCuentaAhorroVista.setVisible(false);
        jPanelCrearCuentaObjetivo.setVisible(false);
        remove(jPanelCearCuentaAhorroVista);
        remove(jPanelCrearCuentaObjetivo);
    }

    private void eliminarFila(JTable table) {
        try {
            tableModelAddres model = (tableModelAddres) table.getModel();
            int row = table.getSelectedRow();
            ///Si se esta escribiendo en la celda para el editor y luego elimina la
            // fila
            if (!model.data.isEmpty()) {
                if (table.isEditing()) {
                    table.getCellEditor().cancelCellEditing();
                    table.revalidate();
                    table.repaint();
                    table.requestFocus();

                }

                model.removeRow(row);
                table.changeSelection(row - 1, 0, false, false);
                table.revalidate();
                table.repaint();
                table.requestFocus();
            }

        } catch (Exception e) {
        }

    }

    private void addRow(JTable table) {
        try {
            tableModelAddres model = (tableModelAddres) table.getModel();

            ///Si se esta escribiendo en la celda para el editor 
            //y luego elimina la fila
            if (!model.data.isEmpty()) {
                if (table.isEditing()) {
                    table.getCellEditor().cancelCellEditing();
                    table.revalidate();
                    table.repaint();
                    table.requestFocus();

                }
            }
            model.addRow(1);
            table.revalidate();
            table.repaint();
            table.requestFocus();
        } catch (Exception e) {
        }

    }

    ArrayList<String> getAddres() {
        ArrayList<String> result = new ArrayList<>();
        for (int i = 0; i < beneciarios.size(); i++) {
            for (int j = 0; j < beneciarios.get(i).length; j++) {
                if (beneciarios.get(i)[j].toString().replace(" ", "") != "") {
                    result.add(beneciarios.get(i)[j].toString());
                }
            }
        }
        return result;
    }

    void setActionIcon(int action) {

        accion = action;

    }

    private boolean validateUI2() {
        if ("".equals(jFormattedTextFieldCIFAhorroObjetivo.getText().
                replace(" ", ""))) {
            return false;
        }
        if ("".equals(jFormattedTextFieldPeriodicidad.getText().
                replace(" ", ""))) {
            return false;
        }
        if ("".equals(jFormattedTextFieldMontoAhorro.getText().
                replace(" ", ""))) {
            return false;
        }
        if ("".equals(jTextFieldCuentaDebito.getText().
                replace(" ", ""))) {
            return false;
        }
        if ("".equals(jFormattedTextFieldProposito.getText().
                replace(" ", ""))) {
            return false;
        }

        return true;

    }

    private ArrayList<ArrayList<String>> cargarPropositos() {
        ArrayList<String> columnas_tabla = new ArrayList<>();
        columnas_tabla.add("CIF");
        columnas_tabla.add("Proposito");
        columnas_tabla.add("TasaInteres");
        try {
            return restfulConnection.getRESTful("http://localhost:52003/api/cbcuenta/getObtenerPropositos", columnas_tabla);
        } catch (Exception e) {
            System.out.println("No se pudo cargar propositos");
        }
        return null;

    }

}
